---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: oci-secrets
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/oracle/oci-secrets-store-csi-driver-provider
    targetRevision: v0.5.0
    path: charts/oci-secrets-store-csi-driver-provider
    helm:
      valuesObject:
        provider:
          image:
            repository: ghcr.io/tradingchassis/oci-secrets-store-csi-driver-provider
            tag: "1f9ef4b6e123c2914edf842d77483d7ee174bf0a"
            pullPolicy: IfNotPresent
          oci:
            auth:
              types:
                instance:
                  enabled: true
                user:
                  enabled: false
                workload:
                  enabled: false
        secrets-store-csi-driver:
          install: true
          linux:
            kubeletRootDir: /var/snap/microk8s/common/var/lib/kubelet
          syncSecret:
            enabled: true
          enableSecretRotation: true

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
